[project]
name = "aider-nix"
version = "0.1.0"
description = "Environment definition for aider-chat for use with Nix"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aider-chat==0.79.1",
]
